pipeline:
  build:
    image: node:latest
    commands:
      - npm i -g yarn
      - yarn install
  test:
    image: node:latest
    environment:
     - NODE_ENV=development
    commands:
      - sleep 20
      - npm test

services:
  database:
    image: mongo
    environment:
      - MONGO_DB=user-service
