pipeline:
  build:
    image: node:latest
    commands:
      - npm i -g yarn
      - yarn install
      - cp .env.example .env
  test:
    image: node:latest
    environment:
     - NODE_ENV=test
    commands:
      - sleep 5
      - npm test

services:
  database:
    image: mongo
    environment:
      - MONGO_DB=user-service
