pipeline:
  build:
    image: node:latest
    commands:
      - npm i -g yarn
      - yarn install
      - yarn sequelize db:migrate
  test:
    image: node:latest
    environment:
     - NODE_ENV=test
    commands:
      - sleep 20
      - npm test

services:
  database:
    image: mongo
